rm(list=ls(all=TRUE))
library(MASS)
library(randomForest)
set.seed(123)
setwd("C:/Users/Affectionate/Desktop")
dataframe<-read.csv('training.csv',header=T,na.strings=c(""))
data<-dataframe[-1]
str(data)
train<-na.roughfix(data)
boxplot(train$ApplicantIncome)
  qnt <- quantile(train$ApplicantIncome, probs=c(.25, .75))
  H <- 1.5 * IQR(train$ApplicantIncome)
  train$ApplicantIncome[train$ApplicantIncome < (qnt[1] - H)] <- mean(train$ApplicantIncome)
  train$ApplicantIncome[train$ApplicantIncome > (qnt[2] + H)] <- mean(train$ApplicantIncome)
boxplot(train$ApplicantIncome)
boxplot(train$CoapplicantIncome)
  qnt <- quantile(train$CoapplicantIncome, probs=c(.25, .75))
  H <- 1.5 * IQR(train$CoapplicantIncome)
 train$CoapplicantIncome[train$CoapplicantIncome < (qnt[1] - H)] <- mean(train$CoapplicantIncome)
  train$CoapplicantIncome[train$CoapplicantIncome > (qnt[2] + H)] <- mean(train$CoapplicantIncome)
  boxplot(train$CoapplicantIncome)
  boxplot(train$LoanAmount)
  qnt <- quantile(train$LoanAmount, probs=c(.25, .75))
  H <- 1.5 * IQR(train$LoanAmount)
 train$LoanAmount[train$LoanAmount < (qnt[1] - H)] <- mean(train$LoanAmount)
  train$LoanAmount[train$LoanAmount > (qnt[2] + H)] <- mean(train$LoanAmount)
  boxplot(train$LoanAmount)
 boxplot(train$Loan_Amount_Term)
  qnt <- quantile(train$Loan_Amount_Term, probs=c(.25, .75))
  H <- 1.5 * IQR(train$Loan_Amount_Term)
 train$LoanAmount[train$Loan_Amount_Term < (qnt[1] - H)] <- mean(train$Loan_Amount_Term)
  train$LoanAmount[train$Loan_Amount_Term > (qnt[2] + H)] <- mean(train$Loan_Amount_Term)
  boxplot(train$Loan_Amount_Term)

modelrandom<-randomForest(Loan_Status~.,data=train,mtry=3,ntree=20)
modelrandom
importance(modelrandom)
varImpPlot(modelrandom)
prediction<-predict(modelrandom,train,type='class')
t<-table(predictions= prediction,actual=train$Loan_Status)
t
correctness<-sum(diag(t))/sum(t)
library(pROC)
predictprob<-predict(modelrandom,train,type='prob')
auc<-auc(train$Loan_Status,predictprob[,2])
plot(roc(train$Loan_Status,predictprob[,2]))
bestmtry<-tuneRF(train,train$Loan_Status,ntreeTry=20,stepFactor=1.2,improve=0.01,trace=T,plot=T)
bestmtry

datatest<-read.csv('test.csv',header=T,na.strings=c(""));str(datatest)
test<-datatest[-1]
str(test)
test.roughfix<-na.roughfix(test)
  qnt <- quantile(test.roughfix$ApplicantIncome, probs=c(.25, .75))
  H <- 1.5 * IQR(test.roughfix$ApplicantIncome)
  test.roughfix$ApplicantIncome[test.roughfix$ApplicantIncome < (qnt[1] - H)] <- mean(test.roughfix$ApplicantIncome)
  test.roughfix$ApplicantIncome[test.roughfix$ApplicantIncome > (qnt[2] + H)] <- mean(test.roughfix$ApplicantIncome)
  boxplot(test.roughfix$ApplicantIncome)
  qnt <- quantile(test.roughfix$CoapplicantIncome, probs=c(.25, .75))
  H <- 1.5 * IQR(test.roughfix$CoapplicantIncome)
  test.roughfix$CoapplicantIncome[test.roughfix$CoapplicantIncome < (qnt[1] - H)] <- mean(test.roughfix$CoapplicantIncome)
  test.roughfix$CoapplicantIncome[test.roughfix$CoapplicantIncome > (qnt[2] + H)] <- mean(test.roughfix$CoapplicantIncome)
  boxplot(test.roughfix$CoapplicantIncome)
  qnt <- quantile(test.roughfix$LoanAmount, probs=c(.25, .75))
  H <- 1.5 * IQR(test.roughfix$LoanAmount)
  test.roughfix$LoanAmount[test.roughfix$LoanAmount < (qnt[1] - H)] <- mean(test.roughfix$LoanAmount)
  test.roughfix$LoanAmount[test.roughfix$LoanAmount > (qnt[2] + H)] <- mean(test.roughfix$LoanAmount)
  boxplot(test.roughfix$LoanAmount)

  qnt <- quantile(test.roughfix$Loan_Amount_Term, probs=c(.25, .75))
  H <- 1.5 * IQR(test.roughfix$Loan_Amount_Term)
  test.roughfix$LoanAmount[test.roughfix$Loan_Amount_Term < (qnt[1] - H)] <- mean(test.roughfix$Loan_Amount_Term)
  test.roughfix$LoanAmount[test.roughfix$Loan_Amount_Term > (qnt[2] + H)] <- mean(test.roughfix$Loan_Amount_Term)
  boxplot(test.roughfix$Loan_Amount_Term)
modelrandom<-randomForest(Loan_Status~.,data=train,mtry=3,ntree=20,keep.forest=TRUE, importance=TRUE,test=test.roughfix)
predicttestprob = predict(modelrandom,type="prob",newdata=test.roughfix)
predicttestclass = predict(modelrandom,type="class",newdata=test.roughfix)
result<-table(predicttestclass)
select1<-table(predicttestprob)
levels(predicttest)
Loan_ID<-as.vector(datatest$Loan_ID)
Loan_Status<-as.vector(predicttestclass)
x<-cbind(Loan_ID,Loan_Status)
write.table(x,file="C:/Users/Affectionate/Desktop/solution_checker2.csv",sep=",",row.names=F,col.names=T)

